CREATE_PETS_TABLE = 'CREATE TABLE IF NOT EXISTS pets(id SERIAL PRIMARY KEY, name VARCHAR(250) NOT NULL, weight DECIMAL(3,1) NOT NULL, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)'



INSERT_NEW_PET = 'INSERT INTO pets(name, weight, user_id, animal_id) VALUES(%s, %s, %s, %s) RETURNING id'